orbs:
  cypress: cypress-io/cypress@1
#  sonarcloud: sonarsource/sonarcloud@1.0.1
version: 2.1

# have a look at https://circleci.com/orbs/registry/orb/germade/rsync
executors:
  cypress-executor:
    docker:
      - image: "cypress/included:5.0.0"
    resource_class: medium+

  cypress-executor-med:
    docker:
      - image: "cypress/included:5.0.0"
    resource_class: medium

jobs:
  deploy:
    docker:
      - image: instrumentisto/rsync-ssh
    resource_class: large
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/
      - run: eval ssh-agent -s
      - run: ssh -o StrictHostKeyChecking=no zz@206.189.241.202 exit
      - run:
          name: Transfer build to digital ocean instance
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then

              rsync -O -ave ssh ~/project/build zz@206.189.241.202:~/insinger-staging
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              rsync -O -ave ssh ~/project/build zz@206.189.241.202:~/insinger-test
            else
              rsync -O -ave ssh ~/project/build zz@206.189.241.202:~/insinger-dev
            fi
  release:
    docker:
      - image: circleci/node:12.14.1-stretch-browsers
    working_directory: ~/project
    steps:
      - checkout
      - run: npx semantic-release

workflows:
  build-and-test:
    jobs:
      - cypress/install:
          executor: cypress-executor
          pre-steps:
            - run:
                name: Set env variables
                command: |
                  if [ "${CIRCLE_BRANCH}" == "master" ]; then
                    echo 'export REACT_APP_PROJECT_URL="$REACT_APP_PROJECT_URL_STAGING"' >> $BASH_ENV
                    echo 'export REACT_APP_CYPRESS_baseUrl="$REACT_APP_PROJECT_URL_STAGING"' >> $BASH_ENV
                    echo 'export REACT_APP_BACKEND_URL="$REACT_APP_BACKEND_URL_STAGING"' >> $BASH_ENV
                  elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
                    echo 'export REACT_APP_PROJECT_URL="https://app.ins.test.nyuki.io"' >> $BASH_ENV
                    echo 'export REACT_APP_CYPRESS_baseUrl="https://app.ins.test.nyuki.io"' >> $BASH_ENV
                    echo 'export REACT_APP_BACKEND_URL="$REACT_APP_BACKEND_URL_TEST"' >> $BASH_ENV
                  else
                    echo 'export REACT_APP_PROJECT_URL="https://app.ins.dev.nyuki.io"' >> $BASH_ENV
                    echo 'export REACT_APP_CYPRESS_baseUrl="https://app.ins.dev.nyuki.io"' >> $BASH_ENV
                    echo 'export REACT_APP_BACKEND_URL="$REACT_APP_BACKEND_URL_DEV"' >> $BASH_ENV
                  fi
                  source $BASH_ENV
          yarn: true
          build: yarn build
      - deploy:
          requires:
            - cypress/install
      - cypress/run:
          executor: cypress-executor
          requires:
            - deploy
          yarn: true
#          command: yarn happo-cypress -- -- yarn cypress run --record --parallel
#          command: yarn cypress:record:chrome
          browser: chrome
          record: true
          parallel: true
          parallelism: 6
          group: "all tests"
      - release:
          requires:
            - deploy
          filters:
            branches:
              only: master
