orbs:
  cypress: cypress-io/cypress@1
version: 2.1

executors:
  test-run-executor:
    docker:
      - image: 'cypress/included:4.5.0'
    resource_class: xlarge

  dev-executor:
    docker:
      - image: 'cypress/included:4.5.0'
    resource_class: xlarge
    environment:
      REACT_APP_BACKEND_PORT: 4201
      REACT_APP_PROJECT_URL: 'https://app.ins.dev.nyuki.io'
      REACT_APP_BACKEND_URL: 'https://app.ins.dev.nyuki.io'
      REACT_APP_MONGO_DB_URL: 'mongodb://localhost:27017/insinger-dev'

  test-executor:
    docker:
      - image: 'cypress/included:4.5.0'
    resource_class: xlarge
    environment:
      REACT_APP_BACKEND_PORT: 4202
      REACT_APP_PROJECT_URL: 'https://app.ins.test.nyuki.io'
      REACT_APP_BACKEND_URL: 'https://app.ins.test.nyuki.io'
      REACT_APP_MONGO_DB_URL: 'mongodb://localhost:27017/insinger-test'

  staging-executor:
    docker:
      - image: 'cypress/included:4.5.0'
    resource_class: xlarge
    environment:
      REACT_APP_BACKEND_PORT: 4200
      REACT_APP_PROJECT_URL: 'https://app.ins.staging.nyuki.io'
      REACT_APP_BACKEND_URL: 'https://app.ins.staging.nyuki.io'
      REACT_APP_MONGO_DB_URL: 'mongodb://localhost:27017/insinger'

jobs:
  deploy-dev:
    docker:
      - image: circleci/node:12.13.0-buster
    resource_class: large
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/
      - run: eval ssh-agent -s
      - run: sudo apt install rsync
      - run: ssh -o StrictHostKeyChecking=no zz@206.189.241.202 exit
      - run: rsync -O -ave ssh ~/project/build zz@206.189.241.202:~/insinger-dev

workflows:
  build-and-test:
    jobs:
      - cypress/install:
          name: Build feature branch
          executor: dev-executor
          yarn: true
          build: yarn build
          filters:
            branches:
              ignore:
                - master
                - develop
                
      - cypress/install:
          name: Build develop branch
          executor: test-executor
          yarn: true
          build: yarn build
          filters:
            branches:
              only:
                - develop

      - cypress/install:
          name: Build master branch
          executor: staging-executor
          yarn: true
          build: yarn build
          filters:
            branches:
              only:
                - master
      - deploy-dev:
          name: Deploy build
          requires:
            - cypress/install
      - cypress/run:
          name: Run cypress tests on deployed build
          executor: test-run-executor
          yarn: true
          browser: chrome
          requires:
            - cypress/install
            - deploy-dev
          record: true
          parallel: true
          parallelism: 11
          group: 'all tests'

