orbs:
  cypress: cypress-io/cypress@1
version: 2.1
# todo: move all ip's to env vars
# todo: make zz orb
#   - circleci_path
#   - ssh_target
#   - ssh_path

executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node12.16.1-chrome80-ff73'
    resource_class: large
jobs:
  deploy-dev:
    docker:
#      - image: circleci/node:12.16.1-buster
      - image: cimg/node:12.16
#      - image: cimg/base:2020.01
    resource_class: large
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/
#      - run: yarn install
      - run:
          name: Load environment variables based on branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo 'export REACT_APP_PROJECT_URL="$REACT_APP_PROJECT_URL_STAGING"' >> $BASH_ENV
              echo 'export REACT_APP_BACKEND_URL="$REACT_APP_BACKEND_URL_STAGING"' >> $BASH_ENV
              echo 'export REACT_APP_BACKEND_PORT="$REACT_APP_BACKEND_PORT_STAGING"' >> $BASH_ENV
              echo 'export REACT_APP_MONGO_DB_URL="$REACT_APP_MONGO_DB_URL_STAGING"' >> $BASH_ENV
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              echo 'export REACT_APP_PROJECT_URL="$REACT_APP_PROJECT_URL_TEST"' >> $BASH_ENV
              echo 'export REACT_APP_BACKEND_URL="$REACT_APP_BACKEND_URL_TEST"' >> $BASH_ENV
              echo 'export REACT_APP_BACKEND_PORT="$REACT_APP_BACKEND_PORT_TEST"' >> $BASH_ENV
              echo 'export REACT_APP_MONGO_DB_URL="$REACT_APP_MONGO_DB_URL_TEST"' >> $BASH_ENV
            else
              echo 'export REACT_APP_PROJECT_URL="$REACT_APP_PROJECT_URL_DEV"' >> $BASH_ENV
              echo 'export REACT_APP_BACKEND_URL="$REACT_APP_BACKEND_URL_DEV"' >> $BASH_ENV
              echo 'export REACT_APP_BACKEND_PORT="$REACT_APP_BACKEND_PORT_DEV"' >> $BASH_ENV
              echo 'export REACT_APP_MONGO_DB_URL="$REACT_APP_MONGO_DB_URL_DEV"' >> $BASH_ENV
            fi
            source $BASH_ENV
#      - run: yarn build
      - run: eval ssh-agent -s
      - run: sudo apt install rsync
      - run: ssh -o StrictHostKeyChecking=no zz@206.189.241.202 exit
#      - run: ssh "$SSH_USER"@"$SSH_HOST_STAGING" "cd ~/insinger-dev/; git checkout .; git pull; git checkout ${CIRCLE_BRANCH}; yarn install;"
      - run: rsync -O -ave ssh ~/project/build zz@206.189.241.202:~/insinger-dev



workflows:
  build-and-test:
    jobs:
      - cypress/install:
          executor: with-chrome
          yarn: true
          build: yarn build
      - deploy-dev:
          requires:
            - cypress/install
      - cypress/run:
          executor: with-chrome
          yarn: true
#          start: yarn serve -s build
#          wait-on: 'http://localhost:300'
          browser: chrome
          requires:
            - cypress/install
#            - deploy-dev
          record: true
          parallel: true
          parallelism: 4
          group: 'all tests'

