orbs:
  cypress: cypress-io/cypress@1
version: 2.1

executors:
  cypress-executor:
    docker:
      - image: 'cypress/included:4.5.0'
    resource_class: xlarge

jobs:
  deploy-dev:
    docker:
      - image: circleci/node:12.13.0-buster
    resource_class: large
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/
      - run: eval ssh-agent -s
      - run: sudo apt install rsync
      - run: ssh -o StrictHostKeyChecking=no zz@206.189.241.202 exit
      - run: rsync -O -ave ssh ~/project/build zz@206.189.241.202:~/insinger-dev

workflows:
  build-and-test:
    jobs:
      - cypress/install:
          executor: cypress-executor
          pre-steps:
            - run:
                name: Set env variables
                command: |
                               if [ "${CIRCLE_BRANCH}" == "master" ]; then
                                 echo 'export REACT_APP_PROJECT_URL="$REACT_APP_PROJECT_URL_STAGING"' >> $BASH_ENV
                                 echo 'export REACT_APP_BACKEND_URL="$REACT_APP_BACKEND_URL_STAGING"' >> $BASH_ENV
                                 echo 'export REACT_APP_BACKEND_PORT="$REACT_APP_BACKEND_PORT_STAGING"' >> $BASH_ENV
                                 echo 'export REACT_APP_MONGO_DB_URL="$REACT_APP_MONGO_DB_URL_STAGING"' >> $BASH_ENV
                               elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
                                 echo 'export REACT_APP_PROJECT_URL="$REACT_APP_PROJECT_URL_TEST"' >> $BASH_ENV
                                 echo 'export REACT_APP_BACKEND_URL="$REACT_APP_BACKEND_URL_TEST"' >> $BASH_ENV
                                 echo 'export REACT_APP_BACKEND_PORT="$REACT_APP_BACKEND_PORT_TEST"' >> $BASH_ENV
                                 echo 'export REACT_APP_MONGO_DB_URL="$REACT_APP_MONGO_DB_URL_TEST"' >> $BASH_ENV
                               else
                                 echo 'export REACT_APP_PROJECT_URL="$REACT_APP_PROJECT_URL_DEV"' >> $BASH_ENV
                                 echo 'export REACT_APP_BACKEND_URL="$REACT_APP_BACKEND_URL_DEV"' >> $BASH_ENV
                                 echo 'export REACT_APP_BACKEND_PORT="$REACT_APP_BACKEND_PORT_DEV"' >> $BASH_ENV
                                 echo 'export REACT_APP_MONGO_DB_URL="$REACT_APP_MONGO_DB_URL_DEV"' >> $BASH_ENV
                               fi
                               source $BASH_ENV
          yarn: true
          build: yarn build

      - deploy-dev:
          requires:
            - cypress/install
      - cypress/run:
          executor: cypress-executor
          yarn: true
          browser: chrome
          requires:
            - cypress/install
            - deploy-dev
          record: true
          parallel: true
          parallelism: 11
          group: 'all tests'

