export const reportsOverviewList = [
  {
    total_target_beneficiaries: 2,
    target_beneficiaries: [
      {
        value: 1,
        _id: '5efdc3c4fa4d696b0fbe92f0',
        name: 'Children/Young people',
        __v: 0,
      },
      {
        value: 0,
        _id: '5efdc3c4fa4d696b0fbe92f1',
        name: 'Elderly',
        __v: 0,
      },
      {
        value: 0,
        _id: '5efdc3c4fa4d696b0fbe92f2',
        name: 'Women',
        __v: 0,
      },
      {
        value: 1,
        _id: '5efdc3c4fa4d696b0fbe92f3',
        name: 'Refugees',
        __v: 0,
      },
      {
        value: 0,
        _id: '5efdc3c4fa4d696b0fbe92f4',
        name: 'Low income individuals',
        __v: 0,
      },
    ],
    total_target_beneficiaries_commited: 10000,
    media: [],
    isDraft: false,
    _id: '5efdc3c4fa4d696b0fbe92f6',
    project: {
      _id: '5e411b96e1886e08a3886dc9',
      project_number: '2018004',
      project_name: 'FFwonen',
      project_description:
        'Het project FFwonen is een kleinschalig project in opbouw, een tussenvoorziening met tijdelijke huisvesting voor de doelgroep â€˜Dakloze in Pakâ€™. Deze doelgroep is door de combinatie van psychosociale problemen en tijdelijke werkloosheid dakloos geraakt. Door het tijdelijk bieden van onderdak en een veilig thuis kunnen zij met minimale begeleiding in korte tijd hun leven weer opbouwen en weer gaan deelnemen aan de samenleving. \nFFwonen is een project van Stichting Dak- en ThuislozenZorg Menorah (voortaan DTZ). Deze interkerkelijke stichting zet zich met inzet van vrijwilligers uit verschillende kerken in voor dak- en thuislozen in Apeldoorn en omgeving zonder onderscheid te maken in religie, afkomst, ras, sekse en geaardheid.',
      duration: '',
      start_date: '',
      end_date: '',
      total_amount: 146181,
      decision_date: '19-3-2018',
      decision: 'Toekenning',
      allocated_amount: 23700,
      released_amount: null,
      paid_amount: 17400,
      organisation: '5e411b95e1886e08a3886d1b',
      category: '5e411b96e1886e08a3886dad',
      __v: 0,
    },
    title: 'repo 1',
    location: null,
    place_name: null,
    date: '7/2/2020',
    country: 'Netherlands',
    policy_priority: {
      _id: '5e664db30552ffe1567c4870',
      name: 'Refugees',
      __v: 0,
    },
    budget: 10000,
    insContribution: 500,
    key_outcomes: 'desc 1',
    monitor_report_outcomes: 'desc 2',
    key_implementation_challenges: 'desc 1',
    other_project_outcomes: 'desc 2',
    plans: 'desc 3',
    other_comments: 'desc 4',
    funder: null,
    reportID: 1043,
    __v: 0,
    unix_date: 1593640800000,
  },
  {
    total_target_beneficiaries: 2,
    target_beneficiaries: [
      {
        value: 1,
        _id: '5efdc41efa4d696b0fbe92f7',
        name: 'Children/Young people',
        __v: 0,
      },
      {
        value: 0,
        _id: '5efdc41efa4d696b0fbe92f8',
        name: 'Elderly',
        __v: 0,
      },
      {
        value: 0,
        _id: '5efdc41efa4d696b0fbe92f9',
        name: 'Women',
        __v: 0,
      },
      {
        value: 1,
        _id: '5efdc41efa4d696b0fbe92fa',
        name: 'Refugees',
        __v: 0,
      },
      {
        value: 0,
        _id: '5efdc41efa4d696b0fbe92fb',
        name: 'Low income individuals',
        __v: 0,
      },
    ],
    total_target_beneficiaries_commited: 10000,
    media: [],
    isDraft: false,
    _id: '5efdc41efa4d696b0fbe92fd',
    project: {
      _id: '5e411b96e1886e08a3886dc1',
      project_number: '2017178',
      project_name: 'restauratie j.h.h. batz orgel 1768',
      project_description:
        'het orgel is hard toe aan een volledige restauratie ( laatste keer is gebeurd in 1971). Er worden regelmatig concerten gegeven.\nVoor de restauratie wordt er een sponsoractie gehouden.',
      duration: '',
      start_date: '',
      end_date: '',
      total_amount: 255000,
      decision_date: '19-3-2018',
      decision: 'Toekenning',
      allocated_amount: 5000,
      released_amount: null,
      paid_amount: 5000,
      organisation: '5e411b95e1886e08a3886cd6',
      category: '5e411b96e1886e08a3886db0',
      __v: 0,
    },
    title: 'repo 2',
    location: null,
    place_name: null,
    date: '7/2/2020',
    country: 'Netherlands',
    policy_priority: {
      _id: '5e664db30552ffe1567c4870',
      name: 'Refugees',
      __v: 0,
    },
    budget: 10000,
    insContribution: 500,
    key_outcomes: 'desc 1',
    monitor_report_outcomes: 'desc 2',
    key_implementation_challenges: 'desc 1',
    other_project_outcomes: 'desc 2',
    plans: 'desc 3',
    other_comments: 'desc 4',
    funder: null,
    reportID: 1044,
    __v: 0,
    unix_date: 1593640800000,
  },
  {
    total_target_beneficiaries: 3,
    target_beneficiaries: [
      {
        value: 1,
        _id: '5eeb4fb8fa4d696b0fbe92ff',
        name: 'Children/Young people',
        __v: 0,
      },
      {
        value: 1,
        _id: '5eeb4fb8fa4d696b0fbe9300',
        name: 'Elderly',
        __v: 0,
      },
      {
        value: 0,
        _id: '5eeb4fb8fa4d696b0fbe9301',
        name: 'Women',
        __v: 0,
      },
      {
        value: 1,
        _id: '5eeb4fb8fa4d696b0fbe9302',
        name: 'Refugees',
        __v: 0,
      },
      {
        value: 0,
        _id: '5eeb4fb8fa4d696b0fbe9303',
        name: 'Low income individuals',
        __v: 0,
      },
    ],
    total_target_beneficiaries_commited: 10000,
    media: [],
    isDraft: false,
    _id: '5eeb4fb8fa4d696b0fbe9305',
    project: {
      _id: '5e42a4d05f9826c33d3e884d',
      project_number: '2019176',
      project_name: 'Inloophuis de Bres Zwolle',
      project_description:
        'De Bres is een bijzonder inloophuis nabij het centrum van Zwolle. Wij bieden laagdrempelige gastvrijheid aan een nog altijd groeiende, brede doelgroep. De bezoekers hebben bijna allemaal in hun eigen omgeving weinig of geen sociale contacten en/of het ontbreekt hen aan een zinvolle invulling van de dag, dit kan leiden tot sterke gevoelens van eenzaamheid. De Bres helpt velen om stabiel te blijven en opgedane contacten te onderhouden. Onze bezoekers ervaren de Bres als een veilige plek in de hectiek van het bestaan.',
      duration: 'Meerjarig',
      start_date: '1-4-2020',
      end_date: '31-12-2020',
      total_amount: 93995,
      decision_date: '18-12-2019',
      decision: 'Toekenning',
      allocated_amount: 7500,
      released_amount: null,
      paid_amount: null,
      organisation: '5e42a4cf5f9826c33d3e8805',
      category: '5e411b96e1886e08a3886db1',
      __v: 0,
    },
    title: 'repo 3',
    location: null,
    place_name: null,
    date: '6/18/2020',
    country: 'Netherlands',
    policy_priority: {
      _id: '5eeb4fb8fa4d696b0fbe92fe',
      name: 'Poverty reduction with a focus on youth and children',
      __v: 0,
    },
    budget: 15000,
    insContribution: 3000,
    key_outcomes: 'desc 1',
    monitor_report_outcomes: 'desc 2',
    key_implementation_challenges: 'desc 1',
    other_project_outcomes: 'desc 2',
    plans: 'desc 3',
    other_comments: 'desc 4',
    funder: null,
    reportID: 1045,
    __v: 0,
    unix_date: 1592431200000,
  },
  {
    total_target_beneficiaries: 1,
    target_beneficiaries: [
      {
        value: 0,
        _id: '5ee75b91fa4d696b0fbe9306',
        name: 'Children/Young people',
        __v: 0,
      },
      {
        value: 1,
        _id: '5ee75b91fa4d696b0fbe9307',
        name: 'Elderly',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ee75b91fa4d696b0fbe9308',
        name: 'Women',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ee75b91fa4d696b0fbe9309',
        name: 'Refugees',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ee75b91fa4d696b0fbe930a',
        name: 'Low income individuals',
        __v: 0,
      },
    ],
    total_target_beneficiaries_commited: 5500,
    media: [],
    isDraft: false,
    _id: '5ee75b91fa4d696b0fbe930c',
    project: {
      _id: '5e411b96e1886e08a3886e09',
      project_number: '2018003',
      project_name: 'Evensong & Engels orgel',
      project_description:
        'Aanschaf, restauratie en completering van een Engels pijporgel voor het organiseren van Evensongs en andere diensten/concerten (o.a. Festival of Lessons and Carols) met een Engels karakter. Gemeenteleden worden betrokken bij de restauratie van het orgel (demontage, schoonmaken, transport, opbouw).',
      duration: '',
      start_date: '',
      end_date: '',
      total_amount: 90000,
      decision_date: '19-3-2018',
      decision: 'Toekenning',
      allocated_amount: 5000,
      released_amount: null,
      paid_amount: 5000,
      organisation: '5e411b95e1886e08a3886cbc',
      category: '5e411b96e1886e08a3886db0',
      __v: 0,
    },
    title: 'repo 5',
    location: null,
    place_name: null,
    date: '6/15/2020',
    country: 'Netherlands',
    policy_priority: {
      _id: '5e4285c69e26862e13f1855b',
      name: 'The Elderly',
      __v: 0,
    },
    budget: 5000,
    insContribution: 500,
    key_outcomes: 'desc 1',
    monitor_report_outcomes: 'desc 2',
    key_implementation_challenges: 'desc 1',
    other_project_outcomes: 'desc 2',
    plans: 'desc 3',
    other_comments: 'desc 4',
    funder: null,
    reportID: 1046,
    __v: 0,
    unix_date: 1592172000000,
  },
  {
    total_target_beneficiaries: 1,
    target_beneficiaries: [
      {
        value: 0,
        _id: '5ef33962fa4d696b0fbe930d',
        name: 'Children/Young people',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ef33962fa4d696b0fbe930e',
        name: 'Elderly',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ef33962fa4d696b0fbe930f',
        name: 'Women',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ef33962fa4d696b0fbe9310',
        name: 'Refugees',
        __v: 0,
      },
      {
        value: 1,
        _id: '5ef33962fa4d696b0fbe9311',
        name: 'Low income individuals',
        __v: 0,
      },
    ],
    total_target_beneficiaries_commited: 800,
    media: [],
    isDraft: false,
    _id: '5ef33962fa4d696b0fbe9313',
    project: {
      _id: '5e411b96e1886e08a3886e01',
      project_number: '2017179',
      project_name: 'The Dynamic Youth',
      project_description:
        'Het jongerengroep is in de kerk ontstaan doordat er  verschillende jongeren met een hulpvraag kwamen. Het initiatief is in 2007 ontstaan met 5 jongeren  en het is nu uitgebreid tot 30 jongeren. Deze jongerengroep kreeg de naam â€˜The Dynamic Youthâ€™. Deze groep is meer wijkgericht dan kerkgericht. Het is een groep jongeren vanuit de wijk en jongeren die naar de kerkdiensten komen. De leeftijd van de jongeren ligt tussen de 12 en 25 jaar. Voor de ontwikkeling van de activiteiten van deze groep werken we met 5 vrijwilligers. Deze vrijwilligers houden zich bezig met het ontplooien en begeleiden van de activiteiten. Om deze groep de kans te bieden om zich te ontwikkelen en zich staande te houden zijn de activiteiten voor de jongeren voldoende uitdagend en zingevend.',
      duration: '',
      start_date: '',
      end_date: '',
      total_amount: 6870,
      decision_date: '19-3-2018',
      decision: 'Toekenning',
      allocated_amount: 2000,
      released_amount: null,
      paid_amount: 2000,
      organisation: '5e411b95e1886e08a3886d06',
      category: '5e411b96e1886e08a3886dad',
      __v: 0,
    },
    title: 'repo 5',
    location: null,
    place_name: null,
    date: '6/24/2020',
    country: 'Netherlands',
    policy_priority: {
      _id: '5eeb4fb8fa4d696b0fbe92fe',
      name: 'Poverty reduction with a focus on youth and children',
      __v: 0,
    },
    budget: 800,
    insContribution: 300,
    key_outcomes: 'desc 1',
    monitor_report_outcomes: 'desc 2',
    key_implementation_challenges: 'desc 1',
    other_project_outcomes: 'desc 2',
    plans: 'desc 3',
    other_comments: 'desc 4',
    funder: null,
    reportID: 1047,
    __v: 0,
    unix_date: 1592949600000,
  },
  {
    total_target_beneficiaries: 1,
    target_beneficiaries: [
      {
        value: 0,
        _id: '5eef453dfa4d696b0fbe9314',
        name: 'Children/Young people',
        __v: 0,
      },
      {
        value: 1,
        _id: '5eef453dfa4d696b0fbe9315',
        name: 'Elderly',
        __v: 0,
      },
      {
        value: 0,
        _id: '5eef453dfa4d696b0fbe9316',
        name: 'Women',
        __v: 0,
      },
      {
        value: 0,
        _id: '5eef453dfa4d696b0fbe9317',
        name: 'Refugees',
        __v: 0,
      },
      {
        value: 0,
        _id: '5eef453dfa4d696b0fbe9318',
        name: 'Low income individuals',
        __v: 0,
      },
    ],
    total_target_beneficiaries_commited: 100000,
    media: [],
    isDraft: false,
    _id: '5eef453dfa4d696b0fbe931a',
    project: {
      _id: '5e411b96e1886e08a3886dff',
      project_number: '2018009',
      project_name: 'Vernieuwingsplekken Remonstranten',
      project_description:
        'De huidige veranderingen in de beleving van kerk-zijn vragen om een antwoord in de vorm van een aanvullend en vernieuwend aanbod op gemeentelijk niveau. \nDe huidige predikanten hebben, gezien de veelheid aan activiteiten in combinatie met de vaak steeds kleiner wordende aanstellingen, onvoldoende ruimte en tijd om de beoogde vernieuwing uit te werken en invulling te geven. Met het opzetten van de zogenaamde vernieuwingsplekken moet voor de bedoelde vernieuwing ruimte worden gegeven.',
      duration: '',
      start_date: '',
      end_date: '',
      total_amount: 410000,
      decision_date: '19-3-2018',
      decision: 'Toekenning',
      allocated_amount: 30000,
      released_amount: null,
      paid_amount: 10000,
      organisation: '5e411b95e1886e08a3886cfd',
      category: '5e411b96e1886e08a3886daf',
      __v: 0,
    },
    title: 'repo 7',
    location: null,
    place_name: null,
    date: '6/21/2020',
    country: 'Netherlands',
    policy_priority: {
      _id: '5e4285c69e26862e13f1855b',
      name: 'The Elderly',
      __v: 0,
    },
    budget: 100000,
    insContribution: 50000,
    key_outcomes: 'desc 1',
    monitor_report_outcomes: 'desc 2',
    key_implementation_challenges: 'desc 1',
    other_project_outcomes: 'desc 1',
    plans: 'desc 1',
    other_comments: 'desc 1',
    funder: null,
    reportID: 1048,
    __v: 0,
    unix_date: 1592690400000,
  },
  {
    total_target_beneficiaries: 1,
    target_beneficiaries: [
      {
        value: 0,
        _id: '5ec66708fa4d696b0fbe931b',
        name: 'Children/Young people',
        __v: 0,
      },
      {
        value: 1,
        _id: '5ec66708fa4d696b0fbe931c',
        name: 'Elderly',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ec66708fa4d696b0fbe931d',
        name: 'Women',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ec66708fa4d696b0fbe931e',
        name: 'Refugees',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ec66708fa4d696b0fbe931f',
        name: 'Low income individuals',
        __v: 0,
      },
    ],
    total_target_beneficiaries_commited: 0,
    media: [],
    isDraft: false,
    _id: '5ec66708fa4d696b0fbe9321',
    project: {
      _id: '5e411b96e1886e08a3886e04',
      project_number: '2017175',
      project_name: 'Pauluskerk Rotterdam projecten 2018',
      project_description:
        'De Pauluskerk Rotterdam streeft naar een gelijke kans op een menswaardig bestaan voor iedereen en zoekt naar wegen om dit mogelijk te maken. Ons doel is om mensen die, om wat voor reden dan ook, leven in de marge van de samenleving nieuw perspectief te bieden en hen te helpen een zinvolle plaats te vinden. \n\nWe (1) helpen daar waar geen helper is, (2) vangen mensen op en helpen hen hun levenskracht te versterken, en (3) vormen een open geloofsgemeenschap (geen onderdeel van deze aanvraag). Onze hulp is hard nodig. Ruim 18% van de Rotterdammers leeft onder de armoedegrens. Dat zijn bijna 120.000 mensen. EÃ©n op de vier Rotterdamse kinderen groeit op in armoede. Zoâ€™n 27.000 Rotterdammers hebben zeer ernstige, problematische schulden. Het aantal daklozen in Nederland groeit al jaren weer en was in 2016 tot 31.000 gestegen. Rotterdam is de stad met de snelst groeiende armoede. Een groeiende groep Rotterdammers redt het niet op eigen kracht. Voor hen is het economische herstel van de laatste jaren nog altijd niet zichtbaar en merkbaar geworden. Ook leeft in de Rotterdamse regio een groot aantal mensen uit Midden- en Oost-Europa. Een deel van hen komt in de problemen wanneer het werk stopt en komt naar de Pauluskerk voor opvang en hulp.\n\nWij vragen uw steun om in 2018 een aantal specifieke activiteiten te kunnen (blijven) uitvoeren, te weten:\n\n1. Helpen waar geen helper is\nDe Pauluskerk biedt (nood)hulp om te voorzien in menselijke basisbehoeften. Daarnaast zet de Pauluskerk zich in voor rechtvaardiger van wet- en regelgeving zodat mensen in de marge van de samenleving niet, buiten hun schuld om, in de marge blijven. Concreet gaat het in 2018 om:\n\n-\tHet Open Huis dat elke dag zoâ€™n 250 mensen verwelkomt en opvangt;\n-\tHet Eethuis dat voorziet in een grote behoefte en 5 keer per week zoâ€™n 50 tot 60 mensen voedt met een maaltijd;\n-\tDe Nachtopvang waar elke nacht tot 24 mensen verblijven;\n-\tCrisisopvang; om in noodgevallen mensen snel van onderdak te voorzien willen we in 2018 beschikken over een kleine crisisopvang, te huren bij een van de woningbouwcorporaties;\n-\tDe maatschappelijke, diaconale, medische en juridische spreekuren, waar honderden mensen per jaar een beroep op doen;\n-\tDe inzet van Pauluskerk voor een rechtvaardiger wet- en regelgeving om de leefomgeving van bezoekers en mensen in de stad structureel te verbeteren, onder andere via de nieuwe projecten Warm Rotterdam en Onvoorwaardelijke Zorgplicht, en via het organiseren van de Rotterdamse Daklozendagen;\n-\tHet organiseren van â€˜dagjes uitâ€™ en het geven van extra aandacht rondom de feestdagen.\n\n2. Versterken levenskracht\nDe Pauluskerk zet, naast alle hulpverlening, expliciet in op het vergroten van de levenskracht van bezoekers, het stimuleren van intermenselijk contact en het bijdragen aan menselijke waardigheid. Daarnaast is de ambitie om waardevolle ontmoetingen te faciliteren tussen â€˜kansarmâ€™ en â€˜kansrijkâ€™, zodat en nieuwe verbindingen ontstaan tussen deze twee vaak langs elkaar levende werelden. De Pauluskerk werkt via twee wegen aan het versterken van levenskracht:\n\n-\tPauluskerk kunst en cultuur:\no\tDit gebeurt onder andere via het nieuwe Culturele Spreekuur, het Open Podium en via culturele werkvormen waaronder schilderen, tekenen, gedichten en verhalen maken, toneel en muzieklessen;\n-\tPauluskerk Zinvolle Dagbesteding en Bouwen aan Waardigheid:\no\tWekelijkse taallessen Nederlands, Engels, en Spaans;\no\tDe computerwerkplaats, waar bezoekers E-learning skills ontwikkelen en een ECDL-certificaat (basiscertificaat computervaardigheden) kunnen behalen;\no\tDe Lunchroom Paulus, de fietsenwerkplaats en vanaf 2018 ook de houtwerkplaats- en winkel. Hier ontwikkelen mensen praktische vaardigheden en ontmoet â€˜kansarmâ€™ en â€˜kansrijkâ€™ elkaar;\no\tDe Kledingwinkel en het Kledingatelier, die (nood)kleding bieden aan iedereen die dit nodig heeft en waar kleding wordt gemaakt en versteld;\no\tActieve deelname aan sport, spel en ontspanning;\n\nEr is geen sprake van overhe',
      duration: '',
      start_date: '',
      end_date: '',
      total_amount: 752441,
      decision_date: '19-3-2018',
      decision: 'Toekenning',
      allocated_amount: 10000,
      released_amount: null,
      paid_amount: 10000,
      organisation: '5e411b95e1886e08a3886cd1',
      category: '5e411b96e1886e08a3886dad',
      __v: 0,
    },
    title: 'repo 8',
    location: null,
    place_name: null,
    date: '5/21/2020',
    country: 'Netherlands',
    policy_priority: {
      _id: '5e4285c69e26862e13f1855b',
      name: 'The Elderly',
      __v: 0,
    },
    budget: 10000,
    insContribution: 5000,
    key_outcomes: 'desc 1',
    monitor_report_outcomes: 'desc 1',
    key_implementation_challenges: 'desc 1',
    other_project_outcomes: 'desc 1',
    plans: 'desc 1',
    other_comments: 'desc 1',
    funder: null,
    reportID: 1049,
    __v: 0,
    unix_date: 1590012000000,
  },
  {
    total_target_beneficiaries: 1,
    target_beneficiaries: [
      {
        value: 0,
        _id: '5ec272c4fa4d696b0fbe9322',
        name: 'Children/Young people',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ec272c4fa4d696b0fbe9323',
        name: 'Elderly',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ec272c4fa4d696b0fbe9324',
        name: 'Women',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ec272c4fa4d696b0fbe9325',
        name: 'Refugees',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ec272c4fa4d696b0fbe9326',
        name: 'Low income individuals',
        __v: 0,
      },
    ],
    total_target_beneficiaries_commited: 1500,
    media: [],
    isDraft: false,
    _id: '5ec272c4fa4d696b0fbe9328',
    project: {
      _id: '5e411b96e1886e08a3886e02',
      project_number: '2017170',
      project_name: 'Pastorale basis',
      project_description:
        'Een goed functionerend wijkpastoraat vereist een solide pastorale basis zodat projecten en activiteiten in de uitvoering worden ondersteund. Een solide pastorale basis is een soort smeermiddel voor de andere activiteiten van wijkpastoraat. De grondhouding van wijkpastoraat is pastorale trouw, trouw richting alle deelnemers. Deze pastorale trouw is een wezenlijk onderdeel van de pastorale basis. De pastorale basis van ons Wijkpastoraat kan worden gerealiseerd door hiervoor een professional 3 dagen per week in te zetten. We voorzien een projectduur van 3 jaar.  Door de werving, training en inzet van vrijwilligers wordt ons Wijkpastoraat zo weinig mogelijk afhankelijk van professionals.',
      duration: '',
      start_date: '',
      end_date: '',
      total_amount: 77000,
      decision_date: '19-3-2018',
      decision: 'Toekenning',
      allocated_amount: 10000,
      released_amount: null,
      paid_amount: 10000,
      organisation: '5e411b95e1886e08a3886d0a',
      category: '5e411b96e1886e08a3886dad',
      __v: 0,
    },
    title: 'repo 9',
    location: null,
    place_name: null,
    date: '5/18/2020',
    country: 'Netherlands',
    policy_priority: {
      _id: '5e4156a9f7c27f21f4a46980',
      name: 'Drug use',
      __v: 0,
    },
    budget: 1000,
    insContribution: 500,
    key_outcomes: 'desc 1',
    monitor_report_outcomes: 'desc 1',
    key_implementation_challenges: 'desc 1',
    other_project_outcomes: 'desc 1',
    plans: 'desc 1',
    other_comments: 'desc 1',
    funder: null,
    reportID: 1050,
    __v: 0,
    unix_date: 1589752800000,
  },
  {
    total_target_beneficiaries: 1,
    target_beneficiaries: [
      {
        value: 0,
        _id: '5ec272f3fa4d696b0fbe932a',
        name: 'Children/Young people',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ec272f3fa4d696b0fbe932b',
        name: 'Elderly',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ec272f3fa4d696b0fbe932c',
        name: 'Women',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ec272f3fa4d696b0fbe932d',
        name: 'Refugees',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ec272f3fa4d696b0fbe932e',
        name: 'Low income individuals',
        __v: 0,
      },
    ],
    total_target_beneficiaries_commited: 20000,
    media: [],
    isDraft: false,
    _id: '5ec272f3fa4d696b0fbe9330',
    project: {
      _id: '5e411b96e1886e08a3886e09',
      project_number: '2018003',
      project_name: 'Evensong & Engels orgel',
      project_description:
        'Aanschaf, restauratie en completering van een Engels pijporgel voor het organiseren van Evensongs en andere diensten/concerten (o.a. Festival of Lessons and Carols) met een Engels karakter. Gemeenteleden worden betrokken bij de restauratie van het orgel (demontage, schoonmaken, transport, opbouw).',
      duration: '',
      start_date: '',
      end_date: '',
      total_amount: 90000,
      decision_date: '19-3-2018',
      decision: 'Toekenning',
      allocated_amount: 5000,
      released_amount: null,
      paid_amount: 5000,
      organisation: '5e411b95e1886e08a3886cbc',
      category: '5e411b96e1886e08a3886db0',
      __v: 0,
    },
    title: 'repo 10',
    location: null,
    place_name: null,
    date: '5/18/2020',
    country: 'Netherlands',
    policy_priority: {
      _id: '5ec272f3fa4d696b0fbe9329',
      name: 'Homelessness',
      __v: 0,
    },
    budget: 25000,
    insContribution: 5000,
    key_outcomes: 'desc 1',
    monitor_report_outcomes: 'desc 1',
    key_implementation_challenges: 'desc 1',
    other_project_outcomes: 'desc 1',
    plans: 'desc 1',
    other_comments: 'desc 1',
    funder: null,
    reportID: 1051,
    __v: 0,
    unix_date: 1589752800000,
  },
  {
    total_target_beneficiaries: 2,
    target_beneficiaries: [
      {
        value: 0,
        _id: '5ead5b3efa4d696b0fbe9331',
        name: 'Children/Young people',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ead5b3efa4d696b0fbe9332',
        name: 'Elderly',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ead5b3efa4d696b0fbe9333',
        name: 'Women',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ead5b3efa4d696b0fbe9334',
        name: 'Refugees',
        __v: 0,
      },
      {
        value: 0,
        _id: '5ead5b3efa4d696b0fbe9335',
        name: 'Low income individuals',
        __v: 0,
      },
    ],
    total_target_beneficiaries_commited: 30000,
    media: [],
    isDraft: false,
    _id: '5ead5b3efa4d696b0fbe9337',
    project: {
      _id: '5e411b96e1886e08a3886dc6',
      project_number: '2017168',
      project_name: 'Herinrichting kind en gezinkamers',
      project_description:
        "herinrichting van voorzieningen voor opvang van kinderen en gezinnen in het kader van nieuwe normering 'Veilige Jeugd'van de maatschappelijke opvang",
      duration: '',
      start_date: '',
      end_date: '',
      total_amount: 70000,
      decision_date: '19-3-2018',
      decision: 'Toekenning',
      allocated_amount: 7000,
      released_amount: null,
      paid_amount: 7000,
      organisation: '5e411b95e1886e08a3886cc8',
      category: '5e411b96e1886e08a3886dad',
      __v: 0,
    },
    title: 'repo 11',
    location: null,
    place_name: null,
    date: '5/2/2020',
    country: 'Netherlands',
    policy_priority: {
      _id: '5e4285c69e26862e13f1855b',
      name: 'The Elderly',
      __v: 0,
    },
    budget: 33000,
    insContribution: 3000,
    key_outcomes: 'desc 1',
    monitor_report_outcomes: 'desc 1',
    key_implementation_challenges: 'desc 1',
    other_project_outcomes: 'desc 1',
    plans: 'desc 1',
    other_comments: 'desc 1',
    funder: null,
    reportID: 1052,
    __v: 0,
    unix_date: 1588370400000,
  },
  {
    total_target_beneficiaries: 5,
    target_beneficiaries: [
      {
        value: 0,
        _id: '5e905a8ffa4d696b0fbe9338',
        name: 'Children/Young people',
        __v: 0,
      },
      {
        value: 0,
        _id: '5e905a8ffa4d696b0fbe9339',
        name: 'Elderly',
        __v: 0,
      },
      {
        value: 0,
        _id: '5e905a8ffa4d696b0fbe933a',
        name: 'Women',
        __v: 0,
      },
      {
        value: 0,
        _id: '5e905a8ffa4d696b0fbe933b',
        name: 'Refugees',
        __v: 0,
      },
      {
        value: 0,
        _id: '5e905a8ffa4d696b0fbe933c',
        name: 'Low income individuals',
        __v: 0,
      },
    ],
    total_target_beneficiaries_commited: 2000,
    media: [],
    isDraft: false,
    _id: '5e905a8ffa4d696b0fbe933e',
    project: {
      _id: '5e411b96e1886e08a3886dd3',
      project_number: '2019016',
      project_name: 'Restauratie topgevels Sint-Janskerk',
      project_description:
        'Het project omvat het restaureren van de topgevels van het koor en de lagere delen van het schip en transept aan de zuidzijde.  Hierbij worden natuursteenonderdelen, zoals pinakels, voetblokken en afdekbanden gedemonteerd en gerestaureerd; voegwerk vervangen c.q. hersteld; muurlood vervangen; geveldelen gereinigd en ontdaan van mos, algen en plantengroei. Het pleisterwerk tussen lood en afdekbanden en in de tussenliggende zakgoten wordt vervangen.',
      duration: 'Eenjarig',
      start_date: '1-4-2019',
      end_date: '31-7-2019',
      total_amount: 283000,
      decision_date: '5-6-2019',
      decision: 'Toekenning',
      allocated_amount: 15000,
      released_amount: null,
      paid_amount: 15000,
      organisation: '5e411b95e1886e08a3886d00',
      category: '5e411b96e1886e08a3886db0',
      __v: 0,
    },
    title: 'repo 12',
    location: null,
    place_name: null,
    date: '4/10/2020',
    country: 'Netherlands',
    policy_priority: {
      _id: '5e4156a9f7c27f21f4a46980',
      name: 'Drug use',
      __v: 0,
    },
    budget: 18000,
    insContribution: 8000,
    key_outcomes: 'desc 1',
    monitor_report_outcomes: 'desc 1',
    key_implementation_challenges: 'desc 1',
    other_project_outcomes: 'desc 1',
    plans: 'desc 1',
    other_comments: 'desc 1',
    funder: null,
    reportID: 1053,
    __v: 0,
    unix_date: 1586469600000,
  },
  {
    total_target_beneficiaries: 2,
    target_beneficiaries: [
      {
        value: 0,
        _id: '5e85ced7fa4d696b0fbe9340',
        name: 'Children/Young people',
        __v: 0,
      },
      {
        value: 0,
        _id: '5e85ced7fa4d696b0fbe9341',
        name: 'Elderly',
        __v: 0,
      },
      {
        value: 0,
        _id: '5e85ced7fa4d696b0fbe9342',
        name: 'Women',
        __v: 0,
      },
      {
        value: 0,
        _id: '5e85ced7fa4d696b0fbe9343',
        name: 'Refugees',
        __v: 0,
      },
      {
        value: 0,
        _id: '5e85ced7fa4d696b0fbe9344',
        name: 'Low income individuals',
        __v: 0,
      },
    ],
    total_target_beneficiaries_commited: 25000,
    media: [],
    isDraft: false,
    _id: '5e85ced7fa4d696b0fbe9346',
    project: {
      _id: '5e411b96e1886e08a3886e15',
      project_number: '2019043',
      project_name: 'Projecten 2019',
      project_description:
        "1. Helpen waar geen helper is\nDe Pauluskerk biedt (nood)hulp om te voorzien in menselijke basisbehoeften. Daarnaast zet de Pauluskerk zich in voor rechtvaardiger van wet- en regelgeving zodat mensen in de marge van de samenleving niet, buiten hun schuld om, in de marge blijven. Projecten oa: Open Huis, Eethuis, Nachtopvang, spreekuren, organiseren 'dagjes uit' en exta aandacht rondom feestdagen.\n\n2. Versterken levenskracht\nDe Pauluskerk zet, naast alle hulpverlening, krachtig in op het vergroten van de levenskracht van bezoekers; het stimuleren van intermenselijk contact en het bijdragen aan menselijke waardigheid, waarmee mensen weer sterker in het leven staan en eerder in staat zijn om het eigen leven weer op te pakken. \nDaarnaast is de ambitie om waardevolle ontmoetingen te faciliteren tussen ‘kansarm’ en ‘kansrijk’, zodat er nieuwe verbindingen ontstaan tussen deze twee vaak langs elkaar levende werelden. De Pauluskerk werkt via twee wegen aan het versterken van levenskracht: Pauluskerk kunst & cultuur (Open Podium, Theateratelier Pauluskerk (NIEUW) en kunstzinnige cursussen) en Pauluskerk Zinvolle Dagbesteding en Bouwen aan Waardigheid (taallessen, lunchroom, kledingwinkel, kledingatelier, kapper (NIEUW), deelname sport en spel.",
      duration: 'Eenjarig',
      start_date: '31-3-2019',
      end_date: '31-12-2019',
      total_amount: 782500,
      decision_date: '5-6-2019',
      decision: 'Toekenning',
      allocated_amount: 10000,
      released_amount: null,
      paid_amount: 9000,
      organisation: '5e411b95e1886e08a3886cd1',
      category: '5e411b96e1886e08a3886db1',
      __v: 0,
    },
    title: 'repo 13',
    location: null,
    place_name: null,
    date: '4/2/2020',
    country: 'Netherlands',
    policy_priority: {
      _id: '5e85ced7fa4d696b0fbe933f',
      name: 'Prisoner rehabilitation / reintegration',
      __v: 0,
    },
    budget: 20000,
    insContribution: 5000,
    key_outcomes: 'desc 1',
    monitor_report_outcomes: 'desc 1',
    key_implementation_challenges: 'desc 1',
    other_project_outcomes: 'desc 1',
    plans: 'desc 1',
    other_comments: 'desc 1',
    funder: null,
    reportID: 1054,
    __v: 0,
    unix_date: 1585778400000,
  },
];
